apiVersion: v1
kind: Pod
metadata:
  name: nginx-users-disallowed
  labels:
    app: nginx-users
spec:
  securityContext:
    supplementalGroups:
      - 0
    fsGroup: 0
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsUser: 0
        runAsGroup: 0